// One-off: build HTML/plain bodies for the Gmail draft and emit them as
// JSON to stdout. The parent runner picks them up and calls the Gmail
// create_draft tool with the result.
import { readFileSync } from "node:fs";
import path from "node:path";

const INPUT_FILE = path.resolve(
  process.cwd(),
  "results",
  "_mobile-discoveries.json"
);

interface Brief {
  product_in_plain_language: string;
  mvp_in_2_weeks: string;
  distribution: string;
  pricing_anchor: string;
  biggest_risk: string;
}

interface Row {
  phrase: string;
  volume: number;
  cpc: number;
  competition: number;
  score: number;
  brief?: Brief;
}

interface MobileFile {
  generated_at: string;
  phrases_total: number;
  phrases_with_signal: number;
  rows: Row[];
}

const data = JSON.parse(readFileSync(INPUT_FILE, "utf8")) as MobileFile;
const ranked = data.rows
  .filter((r) => r.score > 0)
  .sort((a, b) => b.score - a.score);
const briefed = ranked.filter((r) => r.brief);

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const generated = new Date(data.generated_at).toLocaleString("en-US", {
  dateStyle: "long",
  timeStyle: "short",
});

// HTML body
const tableRows = ranked
  .slice(0, 25)
  .map(
    (r, i) =>
      `<tr><td>${i + 1}</td><td>${escapeHtml(r.phrase)}</td><td style="text-align:right">${r.volume.toLocaleString()}</td><td style="text-align:right">$${r.cpc.toFixed(2)}</td><td style="text-align:right">${r.competition.toFixed(2)}</td><td style="text-align:right">${r.score.toFixed(1)}</td></tr>`
  )
  .join("\n");

const briefBlocks = briefed
  .slice(0, 15)
  .map(
    (r, i) => `
<h3 style="margin-bottom:4px">${i + 1}. ${escapeHtml(r.phrase)}</h3>
<p style="color:#475569;margin-top:0;font-size:13px">Vol ${r.volume.toLocaleString()}/mo · CPC $${r.cpc.toFixed(2)} · Competition ${r.competition.toFixed(2)} · Score ${r.score.toFixed(1)}</p>
<p><strong>What the buyer wants.</strong> ${escapeHtml(r.brief!.product_in_plain_language)}</p>
<p><strong>2-week MVP.</strong> ${escapeHtml(r.brief!.mvp_in_2_weeks)}</p>
<p><strong>How to reach them.</strong> ${escapeHtml(r.brief!.distribution)}</p>
<p><strong>Pricing anchor.</strong> ${escapeHtml(r.brief!.pricing_anchor)}</p>
<p><strong style="color:#9F1239">Biggest risk.</strong> ${escapeHtml(r.brief!.biggest_risk)}</p>
<hr style="border:none;border-top:1px solid #E2E8F0;margin:16px 0">
`
  )
  .join("\n");

const html = `
<div style="font-family:-apple-system,system-ui,sans-serif;max-width:720px;line-height:1.5;color:#0F172A">
<h1 style="margin-bottom:4px">Mobile App PMF Report</h1>
<p style="color:#475569;margin-top:0">Generated ${generated} · DataForSEO-backed signals</p>
<p>${data.phrases_total} consumer-mobile phrases scanned, ${data.phrases_with_signal} with non-zero signal (${Math.round((data.phrases_with_signal / data.phrases_total) * 100)}%). Top niches below, ranked by score = log10(vol+1) × min(CPC, 100) × (1 − competition_index).</p>
<h2>Top 25 mobile-app niches</h2>
<table style="border-collapse:collapse;font-size:13px;width:100%">
<thead style="background:#F1F5F9"><tr><th style="text-align:left;padding:6px">#</th><th style="text-align:left;padding:6px">Phrase</th><th style="text-align:right;padding:6px">Vol/mo</th><th style="text-align:right;padding:6px">CPC</th><th style="text-align:right;padding:6px">Comp</th><th style="text-align:right;padding:6px">Score</th></tr></thead>
<tbody>
${tableRows}
</tbody>
</table>
<h2 style="margin-top:32px">Top 15 niches — full briefs</h2>
<p style="color:#475569">For each, the model answered: what is the buyer trying to buy, what could a solo founder ship in 2 weeks, how to reach them, what to charge, and what kills the idea.</p>
${briefBlocks}
<p style="color:#64748B;font-size:12px">Full 30-brief version is available locally as <code>results/mobile-pmf-report.docx</code>. Gmail drafts don't support attachments programmatically yet — open and attach manually before sending if you want the Word version on the recipient end.</p>
<p style="color:#64748B;font-size:12px">Generated by Google Demand Radar · ${ranked.length} ranked niches total.</p>
</div>
`;

// Plain-text fallback
const textRows = ranked
  .slice(0, 25)
  .map(
    (r, i) =>
      `  ${(i + 1).toString().padStart(2)}. ${r.phrase.padEnd(40)} vol ${r.volume.toString().padStart(8)} · cpc $${r.cpc.toFixed(2).padStart(6)} · comp ${r.competition.toFixed(2)} · score ${r.score.toFixed(1)}`
  )
  .join("\n");

const textBriefBlocks = briefed
  .slice(0, 15)
  .map(
    (r, i) => `
${i + 1}. ${r.phrase}
   Vol ${r.volume.toLocaleString()}/mo | CPC $${r.cpc.toFixed(2)} | Comp ${r.competition.toFixed(2)} | Score ${r.score.toFixed(1)}

   WHAT THE BUYER WANTS: ${r.brief!.product_in_plain_language}

   2-WEEK MVP: ${r.brief!.mvp_in_2_weeks}

   HOW TO REACH THEM: ${r.brief!.distribution}

   PRICING ANCHOR: ${r.brief!.pricing_anchor}

   BIGGEST RISK: ${r.brief!.biggest_risk}
`
  )
  .join("\n---\n");

const text = `Mobile App PMF Report
Generated ${generated} · DataForSEO-backed signals

${data.phrases_total} consumer-mobile phrases scanned, ${data.phrases_with_signal} with non-zero signal (${Math.round((data.phrases_with_signal / data.phrases_total) * 100)}%). Top niches below, ranked by score = log10(vol+1) × min(CPC, 100) × (1 − competition_index).

TOP 25 MOBILE-APP NICHES
${textRows}

TOP 15 NICHES — FULL BRIEFS
${textBriefBlocks}

Full 30-brief version is available locally as results/mobile-pmf-report.docx.

Generated by Google Demand Radar. ${ranked.length} ranked niches total.
`;

const subject = `Mobile App PMF Report — top ${briefed.length} niches by demand × CPC × low competition`;

process.stdout.write(
  JSON.stringify({ subject, html, text, briefedCount: briefed.length, rankedCount: ranked.length })
);
